// File: dff.v
// Generated by MyHDL 0.11
// Date: Wed Sep  9 15:29:27 2020


`timescale 1ns/10ps

module dff (
    q,
    d,
    clk
);


output q;
reg q;
input d;
input clk;




always @(posedge clk) begin: DFF_LOGIC
    q <= d;
end

endmodule
